import { getSettings } from "@/lib/repos/settings";
import { site as defaults } from "@/lib/site";
import type { EventItem, Post } from "@/lib/types";

/**
 * Structured data.
 *
 * Google uses these to render the knowledge panel, event listings and article
 * cards. Two rules kept throughout: emit only facts also visible on the page,
 * and use the NGO type rather than the generic Organization — it is the one
 * Google associates with non-profits.
 */

function JsonLd({ data }: { data: Record<string, unknown> }) {
  return (
    <script
      type="application/ld+json"
      // Content is generated by us, not user input; the escape guards against
      // a stray "</script>" sequence appearing inside any text field.
      dangerouslySetInnerHTML={{
        __html: JSON.stringify(data).replace(/</g, "\\u003c"),
      }}
    />
  );
}

export async function OrganizationJsonLd() {
  const site = await getSettings();

  return (
    <JsonLd
      data={{
        "@context": "https://schema.org",
        "@type": "NGO",
        "@id": `${site.url}/#organization`,
        name: site.name,
        alternateName: site.shortName,
        legalName: site.legalName,
        url: site.url,
        description: site.description,
        foundingDate: site.founded,
        slogan: site.tagline,
        email: site.contact.email,
        telephone: site.contact.phone,
        address: {
          "@type": "PostalAddress",
          streetAddress: site.contact.address.street,
          addressLocality: site.contact.address.locality,
          addressRegion: site.contact.address.region,
          postalCode: site.contact.address.postalCode,
          addressCountry: site.contact.address.country,
        },
        areaServed: { "@type": "Country", name: "Kenya" },
        identifier: [
          {
            "@type": "PropertyValue",
            name: site.registration.label,
            value: site.registration.number,
          },
          {
            "@type": "PropertyValue",
            name: site.registration.taxLabel,
            value: site.registration.taxNumber,
          },
        ],
        knowsAbout: [
          "HIV prevention",
          "HIV testing and counselling",
          "Tuberculosis screening",
          "Cervical cancer screening",
          "Breast cancer awareness",
          "Gender-based violence response",
          "HPV vaccination",
          "Menstrual health",
          "Adolescent girls and young women",
        ],
        sameAs: Object.values(site.social),
        potentialAction: {
          "@type": "DonateAction",
          target: `${site.url}/donate`,
          name: `Donate to ${site.name}`,
        },
      }}
    />
  );
}

export function WebsiteJsonLd() {
  const site = defaults;

  return (
    <JsonLd
      data={{
        "@context": "https://schema.org",
        "@type": "WebSite",
        "@id": `${site.url}/#website`,
        url: site.url,
        name: site.name,
        publisher: { "@id": `${site.url}/#organization` },
        potentialAction: {
          "@type": "SearchAction",
          target: {
            "@type": "EntryPoint",
            urlTemplate: `${site.url}/news?q={search_term_string}`,
          },
          "query-input": "required name=search_term_string",
        },
      }}
    />
  );
}

export function ArticleJsonLd({ post }: { post: Post }) {
  const site = defaults;

  return (
    <JsonLd
      data={{
        "@context": "https://schema.org",
        "@type": post.kind === "report" ? "Report" : "NewsArticle",
        headline: post.title,
        description: post.excerpt,
        datePublished: post.published_at,
        dateModified: post.published_at,
        author: post.author_name
          ? { "@type": "Person", name: post.author_name }
          : { "@id": `${site.url}/#organization` },
        publisher: { "@id": `${site.url}/#organization` },
        mainEntityOfPage: `${site.url}/news/${post.slug}`,
        ...(post.cover_image ? { image: [post.cover_image] } : {}),
      }}
    />
  );
}

export function EventJsonLd({ event }: { event: EventItem }) {
  const site = defaults;

  return (
    <JsonLd
      data={{
        "@context": "https://schema.org",
        "@type": "Event",
        name: event.title,
        description: event.summary,
        startDate: event.starts_at,
        ...(event.ends_at ? { endDate: event.ends_at } : {}),
        eventStatus: "https://schema.org/EventScheduled",
        eventAttendanceMode: "https://schema.org/OfflineEventAttendanceMode",
        location: {
          "@type": "Place",
          name: event.venue,
          address: { "@type": "PostalAddress", addressLocality: event.location },
        },
        organizer: { "@id": `${site.url}/#organization` },
        // Our events are free to attend; saying so explicitly is what makes
        // Google render the event card rather than skip it.
        isAccessibleForFree: true,
        offers: {
          "@type": "Offer",
          price: 0,
          priceCurrency: "KES",
          availability: "https://schema.org/InStock",
          url: `${site.url}/events/${event.slug}`,
        },
      }}
    />
  );
}

export function BreadcrumbJsonLd({ trail }: { trail: { name: string; href: string }[] }) {
  const site = defaults;

  return (
    <JsonLd
      data={{
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        itemListElement: trail.map((item, i) => ({
          "@type": "ListItem",
          position: i + 1,
          name: item.name,
          item: `${site.url}${item.href}`,
        })),
      }}
    />
  );
}

export function FaqJsonLd({ faqs }: { faqs: { q: string; a: string }[] }) {
  return (
    <JsonLd
      data={{
        "@context": "https://schema.org",
        "@type": "FAQPage",
        mainEntity: faqs.map((f) => ({
          "@type": "Question",
          name: f.q,
          acceptedAnswer: { "@type": "Answer", text: f.a },
        })),
      }}
    />
  );
}
